CC = gcc

all: array simple complex

array: array.c
	$(CC) -o a.out array.c
	$(CC) -S array.c

simple: standard.c
	$(CC) -o b.out standard.c
	$(CC) -S standard.c

complex: complex.c
	$(CC) -o c.out complex.c
	$(CC) -S complex.c
